// VERBATIM captures from the live Knesset website API (2026-06-10), trimmed
// to representative subsets. These ground the test row-builders in real
// shapes — refresh by re-running the curl commands in the plan (§5) if the
// service shape ever drifts. Do not hand-edit values.
import type { WsVoteDetailsResponse, WsVotesHeadersResponse } from "./website-types";

/** GetVotesHeaders 2026-06-01..10 — the 4 vote-type exemplars only. */
export const CAPTURED_HEADERS = {"Table":[{"VoteId":46078,"VoteProtocolNo":8,"VoteDate":"2026-06-09T19:00:00","VoteDateStr":"9.6.2026","VoteTimeStr":"19:00","VoteDateLongStr":"","VoteType":"אלקטרונית","ItemTitle":"חוק הכרה בתרומתם של כלבים ששירתו בגופים ביטחוניים, התשפ\"ו–2026","KnessetId":25,"SessionId":2243620},{"VoteId":46063,"VoteProtocolNo":null,"VoteDate":"2026-06-08T00:00:00","VoteDateStr":"8.6.2026","VoteTimeStr":"00:00","VoteDateLongStr":"","VoteType":"הרמת יד","ItemTitle":"חוק להקפאת כספים ששילמה הרשות הפלסטינית בזיקה לטרור מהכספים המועברים אליה מממשלת ישראל (תיקון), התשפ\"ו–2026","KnessetId":25,"SessionId":2243619},{"VoteId":46051,"VoteProtocolNo":null,"VoteDate":"2026-06-03T16:27:00","VoteDateStr":"3.6.2026","VoteTimeStr":"16:27","VoteDateLongStr":"","VoteType":"חשאית","ItemTitle":"בחירת מבקר המדינה","KnessetId":25,"SessionId":2243819},{"VoteId":46052,"VoteProtocolNo":null,"VoteDate":"2026-06-03T00:00:00","VoteDateStr":"3.6.2026","VoteTimeStr":"00:00","VoteDateLongStr":"","VoteType":"שמית","ItemTitle":"הצעת חוק האזרחים הוותיקים (תיקון - תגמול מחיה לאזרחים ותיקים), התשפ\"ו-2026","KnessetId":25,"SessionId":2243511}]} as unknown as WsVotesHeadersResponse;

/** GetVoteDetails/46078 — electronic, 5 voters, all בעד (id 7). */
export const CAPTURED_DETAIL_ELECTRONIC = {"VoteHeader":[{"VoteId":46078,"VoteProtocolNo":8,"VoteDate":"2026-06-09T19:00:00","VoteDateStr":"9.6.2026","VoteTimeStr":"19:00","VoteType":"הצבעה אלקטרונית","VoteTypeId":1,"ItemTitle":"חוק הכרה בתרומתם של כלבים ששירתו בגופים ביטחוניים, התשפ\"ו–2026","FK_ItemID":2217042,"FK_AssemblyID":163,"LU_ItemType":2,"SessionNumber":402,"FK_Knesset":25,"Decision":"לקבל בקריאה שנייה","ChairmanName":"סימון דוידסון","DescreetVoteType":null,"IsForAccepted":true,"AcceptedText":"ההצעה התקבלה"}],"VoteCounters":[{"Title":"בעד","countOfResult":5,"rn":1,"ColorName":"#0A3542"}],"VoteDetails":[{"MkName":"אזולאי ינון","FactionName":"התאחדות הספרדים שומרי תורה תנועתו של מרן הרב עובדיה יוסף זצ\"ל","VoteResultId":7,"Title":"בעד"},{"MkName":"אלקין זאב","FactionName":"הימין הממלכתי ","VoteResultId":7,"Title":"בעד"},{"MkName":"דוידסון סימון","FactionName":"יש עתיד","VoteResultId":7,"Title":"בעד"},{"MkName":"כץ אופיר","FactionName":"הליכוד ","VoteResultId":7,"Title":"בעד"},{"MkName":"לוי מיקי","FactionName":"יש עתיד","VoteResultId":7,"Title":"בעד"}],"DescreetVoteResults":[],"HandsWithoutCountersAccepted":[],"NextAndPrevVotes":[{"NextVote":null,"PrevVote":46076}]} as unknown as WsVoteDetailsResponse;

/** GetVoteDetails/46063 — hand vote ("הרמת ידיים עם מונים"): counters, NO per-MK rows. */
export const CAPTURED_DETAIL_HAND = {"VoteHeader":[{"VoteId":46063,"VoteProtocolNo":null,"VoteDate":"2026-06-08T00:00:00","VoteDateStr":"8.6.2026","VoteTimeStr":"00:00","VoteType":"הרמת ידיים עם מונים","VoteTypeId":4,"ItemTitle":"חוק להקפאת כספים ששילמה הרשות הפלסטינית בזיקה לטרור מהכספים המועברים אליה מממשלת ישראל (תיקון), התשפ\"ו–2026","FK_ItemID":2220111,"FK_AssemblyID":164,"LU_ItemType":2,"SessionNumber":401,"FK_Knesset":25,"KnessetName":" העשרים-וחמש","Decision":"לקבל בקריאה שנייה","ChairmanName":"אליהו רביבו","DescreetVoteType":null,"IsForAccepted":true,"AcceptedText":"ההצעה התקבלה"}],"VoteCounters":[{"Title":"נמנע","countOfResult":0,"rn":1,"ColorName":"#0A3542"},{"Title":"נגד","countOfResult":5,"rn":2,"ColorName":"#507282"},{"Title":"בעד","countOfResult":28,"rn":3,"ColorName":"#9F2214"}],"VoteDetails":[],"DescreetVoteResults":[],"HandsWithoutCountersAccepted":[],"NextAndPrevVotes":[{"NextVote":46071,"PrevVote":46049}]} as unknown as WsVoteDetailsResponse;

/** GetVoteDetails/46052 — roll-call (שמית), trimmed to 6 of 83 rows (ids 7/8). */
export const CAPTURED_DETAIL_ROLL_CALL = {"VoteHeader":[{"VoteId":46052,"VoteProtocolNo":null,"VoteDate":"2026-06-03T00:00:00","VoteDateStr":"3.6.2026","VoteTimeStr":"00:00","VoteType":"שמית","VoteTypeId":2,"ItemTitle":"הצעת חוק האזרחים הוותיקים (תיקון - תגמול מחיה לאזרחים ותיקים), התשפ\"ו-2026","FK_ItemID":2240133,"FK_AssemblyID":167,"LU_ItemType":2,"SessionNumber":400,"FK_Knesset":25,"KnessetName":" העשרים-וחמש","Decision":"לדחות את ההצעה","ChairmanName":"אליהו רביבו","DescreetVoteType":null,"IsForAccepted":false,"AcceptedText":"ההצעה לא התקבלה"}],"VoteCounters":[{"Title":"בעד","countOfResult":34,"rn":1,"ColorName":"#0A3542"},{"Title":"נגד","countOfResult":49,"rn":2,"ColorName":"#507282"}],"VoteDetails":[{"MkName":"אבוטבול משה","FactionName":"התאחדות הספרדים שומרי תורה תנועתו של מרן הרב עובדיה יוסף זצ\"ל","VoteResultId":8,"Title":"נגד"},{"MkName":"אוחנה אמיר","FactionName":"הליכוד ","VoteResultId":8,"Title":"נגד"},{"MkName":"אילוז דן","FactionName":"הליכוד ","VoteResultId":8,"Title":"נגד"},{"MkName":"אלהרר קארין","FactionName":"יש עתיד","VoteResultId":7,"Title":"בעד"},{"MkName":"אליהו עמיחי","FactionName":"עוצמה יהודית בראשות איתמר בן גביר","VoteResultId":8,"Title":"נגד"},{"MkName":"אלקין זאב","FactionName":"הימין הממלכתי ","VoteResultId":8,"Title":"נגד"}],"DescreetVoteResults":[],"HandsWithoutCountersAccepted":[],"NextAndPrevVotes":[{"NextVote":46050,"PrevVote":46008}]} as unknown as WsVoteDetailsResponse;

/** GetVoteDetails/46051 — secret (חשאית): no counters, candidate totals only. */
export const CAPTURED_DETAIL_SECRET = {"VoteHeader":[{"VoteId":46051,"VoteProtocolNo":null,"VoteDate":"2026-06-03T16:27:00","VoteDateStr":"3.6.2026","VoteTimeStr":"16:27","VoteType":"חשאית","VoteTypeId":3,"ItemTitle":"ישיבה מיוחדת לבחירת מבקר המדינה","FK_ItemID":2243820,"FK_AssemblyID":168,"LU_ItemType":9,"SessionNumber":399,"FK_Knesset":25,"KnessetName":" העשרים-וחמש","Decision":null,"ChairmanName":"אמיר אוחנה","DescreetVoteType":"בחירת מבקר המדינה","IsForAccepted":true,"AcceptedText":"ההצעה התקבלה"}],"VoteCounters":[],"VoteDetails":[],"DescreetVoteResults":[{"ID":34,"FK_VoteID":46051,"description":"יוסף אלרון","AmountFor":57,"IsSingleNominee":false,"AmountAgainst":0,"rn":1,"ColorName":"#0A3542"},{"ID":33,"FK_VoteID":46051,"description":"מיכאל ראבילו ","AmountFor":61,"IsSingleNominee":false,"AmountAgainst":0,"rn":2,"ColorName":"#507282"}],"HandsWithoutCountersAccepted":[],"NextAndPrevVotes":[{"NextVote":46019,"PrevVote":46050}]} as unknown as WsVoteDetailsResponse;
